//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geekbot.Core.Localization {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cookies {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Cookies() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Geekbot.Core.Localization.Cookies", typeof(Cookies).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string GetCookies {
            get {
                return ResourceManager.GetString("GetCookies", resourceCulture);
            }
        }
        
        public static string WaitForMoreCookies {
            get {
                return ResourceManager.GetString("WaitForMoreCookies", resourceCulture);
            }
        }
        
        public static string InYourJar {
            get {
                return ResourceManager.GetString("InYourJar", resourceCulture);
            }
        }
        
        public static string Given {
            get {
                return ResourceManager.GetString("Given", resourceCulture);
            }
        }
        
        public static string NotEnoughToGive {
            get {
                return ResourceManager.GetString("NotEnoughToGive", resourceCulture);
            }
        }
        
        public static string NotEnoughCookiesToEat {
            get {
                return ResourceManager.GetString("NotEnoughCookiesToEat", resourceCulture);
            }
        }
        
        public static string AteCookies {
            get {
                return ResourceManager.GetString("AteCookies", resourceCulture);
            }
        }
        
        public static string CantTakeCookies {
            get {
                return ResourceManager.GetString("CantTakeCookies", resourceCulture);
            }
        }
    }
}
