//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geekbot.Core.Localization {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ship {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Ship() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geekbot.Core.Localization.Ship", typeof(Ship).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost a match.
        /// </summary>
        public static string CouldWork {
            get {
                return ResourceManager.GetString("CouldWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a match.
        /// </summary>
        public static string ItsAMatch {
            get {
                return ResourceManager.GetString("ItsAMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matchmaking.
        /// </summary>
        public static string Matchmaking {
            get {
                return ResourceManager.GetString("Matchmaking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not going happen.
        /// </summary>
        public static string NotGoingToHappen {
            get {
                return ResourceManager.GetString("NotGoingToHappen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not such a good idea.
        /// </summary>
        public static string NotSuchAGoodIdea {
            get {
                return ResourceManager.GetString("NotSuchAGoodIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There might be a chance.
        /// </summary>
        public static string ThereMightBeAChance {
            get {
                return ResourceManager.GetString("ThereMightBeAChance", resourceCulture);
            }
        }
    }
}
