//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geekbot.Bot.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EightBall {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EightBall() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geekbot.Bot.Localization.EightBall", typeof(EightBall).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As I see it, yes.
        /// </summary>
        internal static string AsISeeItYes {
            get {
                return ResourceManager.GetString("AsISeeItYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask again later.
        /// </summary>
        internal static string AskAgainLater {
            get {
                return ResourceManager.GetString("AskAgainLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Better not tell you now.
        /// </summary>
        internal static string BetterNotTellYouNow {
            get {
                return ResourceManager.GetString("BetterNotTellYouNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot predict now.
        /// </summary>
        internal static string CannotPredictNow {
            get {
                return ResourceManager.GetString("CannotPredictNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentrate and ask again.
        /// </summary>
        internal static string ConcentrateAndAskAgain {
            get {
                return ResourceManager.GetString("ConcentrateAndAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t count on it.
        /// </summary>
        internal static string DontCountOnIt {
            get {
                return ResourceManager.GetString("DontCountOnIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is certain.
        /// </summary>
        internal static string ItIsCertain {
            get {
                return ResourceManager.GetString("ItIsCertain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is decidedly so.
        /// </summary>
        internal static string ItIsDecidedlySo {
            get {
                return ResourceManager.GetString("ItIsDecidedlySo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most likely.
        /// </summary>
        internal static string MostLikely {
            get {
                return ResourceManager.GetString("MostLikely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reply is no.
        /// </summary>
        internal static string MyReplyIsNo {
            get {
                return ResourceManager.GetString("MyReplyIsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My sources say no.
        /// </summary>
        internal static string MySourcesSayNo {
            get {
                return ResourceManager.GetString("MySourcesSayNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook good.
        /// </summary>
        internal static string OutlookGood {
            get {
                return ResourceManager.GetString("OutlookGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook not so good.
        /// </summary>
        internal static string OutlookNotSoGood {
            get {
                return ResourceManager.GetString("OutlookNotSoGood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply hazy try again.
        /// </summary>
        internal static string ReplyHazyTryAgain {
            get {
                return ResourceManager.GetString("ReplyHazyTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signs point to yes.
        /// </summary>
        internal static string SignsPointToYes {
            get {
                return ResourceManager.GetString("SignsPointToYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very doubtful.
        /// </summary>
        internal static string VeryDoubtful {
            get {
                return ResourceManager.GetString("VeryDoubtful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without a doubt.
        /// </summary>
        internal static string WithoutADoubt {
            get {
                return ResourceManager.GetString("WithoutADoubt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, definitely.
        /// </summary>
        internal static string YesDefinitely {
            get {
                return ResourceManager.GetString("YesDefinitely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may rely on it.
        /// </summary>
        internal static string YouMayRelyOnIt {
            get {
                return ResourceManager.GetString("YouMayRelyOnIt", resourceCulture);
            }
        }
    }
}
