//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geekbot.Bot.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Quote {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Quote() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geekbot.Bot.Localization.Quote", typeof(Quote).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t save quotes by a bot....
        /// </summary>
        internal static string CannotQuoteBots {
            get {
                return ResourceManager.GetString("CannotQuoteBots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t save your own quotes....
        /// </summary>
        internal static string CannotSaveOwnQuotes {
            get {
                return ResourceManager.GetString("CannotSaveOwnQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most quoted person.
        /// </summary>
        internal static string MostQuotesPerson {
            get {
                return ResourceManager.GetString("MostQuotesPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This server doesn&apos;t seem to have any quotes yet. You can add a quote with `!quote save @user` or `!quote save &lt;messageId&gt;`.
        /// </summary>
        internal static string NoQuotesFound {
            get {
                return ResourceManager.GetString("NoQuotesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is not a valid message link.
        /// </summary>
        internal static string NotAValidMessageLink {
            get {
                return ResourceManager.GetString("NotAValidMessageLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t find a quote with that ID :disappointed:.
        /// </summary>
        internal static string NotFoundWithId {
            get {
                return ResourceManager.GetString("NotFoundWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only quote messages from the same server.
        /// </summary>
        internal static string OnlyQuoteFromSameServer {
            get {
                return ResourceManager.GetString("OnlyQuoteFromSameServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Quote Added**.
        /// </summary>
        internal static string QuoteAdded {
            get {
                return ResourceManager.GetString("QuoteAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote Stats.
        /// </summary>
        internal static string QuoteStats {
            get {
                return ResourceManager.GetString("QuoteStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Removed #{0}**.
        /// </summary>
        internal static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string TotalQuotes {
            get {
                return ResourceManager.GetString("TotalQuotes", resourceCulture);
            }
        }
    }
}
