//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Geekbot.Bot.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Role {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Role() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Geekbot.Bot.Localization.Role", typeof(Role).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added {0} to the whitelist.
        /// </summary>
        internal static string AddedRoleToWhitelist {
            get {
                return ResourceManager.GetString("AddedRoleToWhitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added you to {0}.
        /// </summary>
        internal static string AddedUserFromRole {
            get {
                return ResourceManager.GetString("AddedUserFromRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add that role to self service because it contains one or more dangerous permissions.
        /// </summary>
        internal static string CannotAddDangerousRole {
            get {
                return ResourceManager.GetString("CannotAddDangerousRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add a role that is managed by discord.
        /// </summary>
        internal static string CannotAddManagedRole {
            get {
                return ResourceManager.GetString("CannotAddManagedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Self Service Roles on {0}**.
        /// </summary>
        internal static string ListHeader {
            get {
                return ResourceManager.GetString("ListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get a role, use `!role [name]`.
        /// </summary>
        internal static string ListInstruction {
            get {
                return ResourceManager.GetString("ListInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no roles configured for this server.
        /// </summary>
        internal static string NoRolesConfigured {
            get {
                return ResourceManager.GetString("NoRolesConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {0} from the whitelist.
        /// </summary>
        internal static string RemovedRoleFromWhitelist {
            get {
                return ResourceManager.GetString("RemovedRoleFromWhitelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed you from {0}.
        /// </summary>
        internal static string RemovedUserFromRole {
            get {
                return ResourceManager.GetString("RemovedUserFromRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That role doesn&apos;t exist or is not on the whitelist.
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
    }
}
